import { ApiBody, ApiConsumes, ApiOperation, ApiParam, ApiQuery, ApiResponse, ApiTags } from '@nestjs/swagger';
import { docs } from 'nestjs-docfy';
import { UsersController } from './users.controller';
import { UserRole } from './entities/user.entity';

docs(UsersController, {
  classDecorators: [ApiTags('users')],
  methods: {
    findAll: [
      ApiOperation({ summary: 'List users', description: 'Optionally filter by role.' }),
      // `enum: UserRole` — a real TS enum, imported from another file, not
      // an array literal. Resolves because generateDocfyMetadata/patch-spec
      // parse every controller's docs file inside the same real project
      // that scanned the controller itself, not an isolated one.
      ApiQuery({ name: 'role', required: false, enum: UserRole }),
      ApiResponse({
        status: 200,
        description: 'OK',
        examples: {
          allUsers: { summary: 'Unfiltered', value: [{ id: '1', name: 'Ada Lovelace', role: 'member' }] },
        },
      }),
    ],

    // No `schema`/`type` given here at all — the 200 response falls back to
    // findOne()'s own resolved return type, Promise<UserEntity |
    // AdminUserEntity>, which patch-spec/the CLI plugin turn into a `oneOf`
    // of the two named schemas automatically.
    findOne: [
      ApiOperation({ summary: 'Find a user by id' }),
      ApiResponse({ status: 200, description: 'A member or admin user' }),
      // An explicit schema here, instead of leaving it to fall back to
      // findOne()'s return type — that fallback applies to *every* response
      // status without an explicit schema/type, which would otherwise put
      // the same "member or admin user" oneOf on a 404 too.
      ApiResponse({
        status: 404,
        description: 'Not found',
        schema: { type: 'object', properties: { message: { type: 'string' }, statusCode: { type: 'number' } } },
      }),
    ],

    create: [
      ApiOperation({ summary: 'Create a user' }),
      // No `schema`/`type` given — falls back to CreateUserDto's own
      // class-validator decorators (@IsString/@IsEmail), inferred into a
      // JSON Schema automatically. See the "class-validator inference"
      // section of the README.
      ApiBody({ description: 'New user payload' }),
      ApiResponse({ status: 201, description: 'Created' }),
    ],

    // Auto-generated by `generate` for the @UploadedFile() param — @ApiConsumes
    // + a binary-format @ApiBody schema, no manual Swagger decorators written
    // for this endpoint. See the "File uploads" section of the README.
    uploadAvatar: [
      ApiOperation({ summary: 'Upload avatar' }),
      ApiParam({ name: 'id', type: String }),
      ApiConsumes('multipart/form-data'),
      ApiBody({ schema: { type: 'object', properties: { file: { type: 'string', format: 'binary' } } } }),
      ApiResponse({ status: 201, description: 'Created' }),
      ApiResponse({ status: 404, description: 'Not found' }),
    ],
  },
});
