import fs from 'fs';
import { deriveDocsFilePath } from './scan-controllers';
import { GENERATED_HEADER_RE } from './generate-file';
import type { ControllerInfo } from './extract-methods';

export interface DocsVersionDrift {
  controllerClass: string;
  docsFile: string;
  /** `null` when the docs file predates version stamping (generated by nestjs-docfy < 0.13.0). */
  stampedVersion: string | null;
}

/** Parses a `MAJOR.MINOR.PATCH` string into a tuple for comparison. Returns `null` for anything
 * that doesn't match — callers treat that the same as "can't tell, don't warn". */
function parseSemver(version: string): [number, number, number] | null {
  const match = /^(\d+)\.(\d+)\.(\d+)/.exec(version);
  if (!match) return null;
  return [Number(match[1]), Number(match[2]), Number(match[3])];
}

/** True when `a` is strictly older than `b`. */
function isOlder(a: [number, number, number], b: [number, number, number]): boolean {
  for (let i = 0; i < 3; i++) {
    if (a[i] !== b[i]) return a[i] < b[i];
  }
  return false;
}

/**
 * Detects the gap in `friccao-backlog.md` item 7: nothing warns when a generated docs file was
 * produced by an older nestjs-docfy than the one currently installed — schema-shape bugs fixed
 * since then (e.g. the `boolean` union collapse) silently keep affecting that file until someone
 * thinks to regenerate it. Compares each docs file's stamped generator version (embedded in its
 * header comment by `generate`) against `currentVersion`; docs files older than the installed
 * lib, or predating version stamping entirely, are reported. `generate --overwrite` is the fix.
 */
export function checkDocsVersionDrift(
  controllers: ControllerInfo[],
  format: 'ts' | 'js',
  currentVersion: string,
): DocsVersionDrift[] {
  const current = parseSemver(currentVersion);
  if (!current) return [];

  const drift: DocsVersionDrift[] = [];
  for (const ctrl of controllers) {
    if (!ctrl.hasDocsFile) continue;
    const docsFile = deriveDocsFilePath(ctrl.filePath, format);

    let content: string;
    try {
      content = fs.readFileSync(docsFile, 'utf8');
    } catch {
      continue;
    }

    const match = GENERATED_HEADER_RE.exec(content);
    if (!match) continue; // not a docfy-generated file (or header was hand-edited away) — nothing to compare

    const stamped = match[1] ?? null;
    const stampedSemver = stamped ? parseSemver(stamped) : null;

    if (stamped === null || (stampedSemver && isOlder(stampedSemver, current))) {
      drift.push({ controllerClass: ctrl.className, docsFile, stampedVersion: stamped });
    }
  }
  return drift;
}
