import openapiTS, { astToString } from 'openapi-typescript';
import type { OpenApiDocument } from './merge-spec-patch';

export interface ClientFiles {
  /** Contents of schema.d.ts — the generated types, via openapi-typescript. */
  schema: string;
  /** Contents of client.ts — a thin typed wrapper over openapi-fetch. */
  client: string;
}

function buildClientWrapper(schemaFileName: string): string {
  return `// Generated by nestjs-docfy generate-client — re-run to update, edit freely otherwise.
// Requires the peer dependency 'openapi-fetch': npm install openapi-fetch
import createClient from 'openapi-fetch';
import type { paths } from './${schemaFileName}';

export function createApiClient(baseUrl: string) {
  return createClient<paths>({ baseUrl });
}
`;
}

/**
 * Generates a typed TypeScript client from an OpenAPI document — a thin
 * wrapper over openapi-typescript (types) + openapi-fetch (the runtime
 * client), rather than a from-scratch code generator. openapi-fetch itself
 * is deliberately NOT a dependency of nestjs-docfy: it's only imported by
 * the generated client.ts, so it belongs in the consuming project.
 */
export async function buildClientFiles(document: OpenApiDocument): Promise<ClientFiles> {
  const ast = await openapiTS(document as any);
  const schema = astToString(ast);
  const client = buildClientWrapper('schema');
  return { schema, client };
}
