import path from 'path';
import type { ControllerInfo, MethodInfo } from './extract-methods';

// ---------------------------------------------------------------------------
// Sanitisation helpers — values from AST go through these before any
// string interpolation so they can never inject executable code.
// ---------------------------------------------------------------------------

/** Whitelist for JS identifiers: letters, digits, $ and _. */
const IDENTIFIER_RE = /^[$_a-zA-Z][$_a-zA-Z0-9]*$/;

function sanitizeIdentifier(value: string, fallback: string): string {
  return IDENTIFIER_RE.test(value) ? value : fallback;
}

/** Strips characters that could close a JS string or inject code into a comment. */
function sanitizeComment(value: string): string {
  return value.replace(/[`'"\\*]/g, '').slice(0, 200);
}

/** Escapes a URL path for safe use inside a line comment. */
function sanitizeHttpPath(value: string | null): string {
  if (!value) return '';
  return '/' + value.replace(/[^a-zA-Z0-9/_:.-]/g, '');
}

// ---------------------------------------------------------------------------
// Import path resolution
// ---------------------------------------------------------------------------

/**
 * Computes the relative import path from the generated docs file to the
 * controller file, stripping the .ts extension (CommonJS/ESM convention).
 */
export function relativeImport(docsFilePath: string, controllerFilePath: string): string {
  const rel = path.relative(path.dirname(docsFilePath), controllerFilePath);
  const withoutExt = rel.replace(/\.ts$/, '');
  // Ensure it starts with ./ for Node module resolution
  return withoutExt.startsWith('.') ? withoutExt : `./${withoutExt}`;
}

// ---------------------------------------------------------------------------
// Method signature comment
// ---------------------------------------------------------------------------

function methodSignatureComment(m: MethodInfo): string {
  const verb = m.httpDecorator ? `${m.httpDecorator.toUpperCase()} ` : '';
  const httpPath = m.httpPath !== null ? sanitizeHttpPath(m.httpPath) : '';
  const route = verb || httpPath ? `${verb}${httpPath} → ` : '';
  const paramList = m.params
    .map((p) => `${sanitizeIdentifier(p.name, '_')}: ${sanitizeComment(p.type)}`)
    .join(', ');
  const returnType = sanitizeComment(m.returnType);
  const asyncPrefix = m.isAsync ? 'async ' : '';
  const methodName = sanitizeIdentifier(m.name, '_');
  const inherited = m.isInherited && m.inheritedFrom
    ? ` [inherited from ${sanitizeComment(m.inheritedFrom)}]`
    : '';
  return `${route}${asyncPrefix}${methodName}(${paramList}): ${returnType}${inherited}`;
}

// ---------------------------------------------------------------------------
// Template
// ---------------------------------------------------------------------------

function renderMethod(m: MethodInfo, indent: string): string {
  const name = sanitizeIdentifier(m.name, '_method');
  const sig = methodSignatureComment(m);
  const lines: string[] = [];
  lines.push(`${indent}// ${sig}`);
  lines.push(`${indent}${name}: [`);
  lines.push(`${indent}  // ApiOperation({ summary: '' }),`);
  lines.push(`${indent}  // ApiResponse({ status: 200 }),`);
  lines.push(`${indent}],`);
  return lines.join('\n');
}

/**
 * Renders a complete .controller.docs.ts file for the given controller.
 * All user-sourced values are sanitised before interpolation.
 */
export function renderDocsFile(
  ctrl: ControllerInfo,
  docsFilePath: string,
  format: 'ts' | 'js',
): string {
  const importPath = relativeImport(docsFilePath, ctrl.filePath);
  const className = sanitizeIdentifier(ctrl.className, 'Controller');
  const controllerRoute = ctrl.controllerPath !== null
    ? ` (route: "${sanitizeHttpPath(ctrl.controllerPath)}")`
    : '';
  const timestamp = new Date().toISOString();

  const methodsBlock = ctrl.methods.length === 0
    ? '  // No public HTTP methods found.'
    : ctrl.methods.map((m) => renderMethod(m, '  ')).join('\n\n');

  if (format === 'js') {
    return [
      `// Auto-generated by nestjs-docfy — fill in the decorator arrays.`,
      `// Generated: ${timestamp}`,
      ``,
      `const { docs } = require('nestjs-docfy');`,
      `const { ${className} } = require('${importPath}');`,
      ``,
      `docs(${className}, {`,
      `  classDecorators: [`,
      `    // ApiTags('${sanitizeComment(ctrl.controllerPath ?? className.replace(/Controller$/, '').toLowerCase())}'),`,
      `  ],`,
      `  methods: {`,
      methodsBlock.split('\n').map((l) => (l ? `  ${l}` : l)).join('\n'),
      `  },`,
      `});`,
      ``,
    ].join('\n');
  }

  return [
    `/**`,
    ` * Auto-generated by nestjs-docfy — fill in the decorator arrays.`,
    ` * Controller: ${className}${controllerRoute}`,
    ` * Generated: ${timestamp}`,
    ` */`,
    `import { docs } from 'nestjs-docfy';`,
    `import { ApiTags, ApiOperation, ApiResponse } from '@nestjs/swagger';`,
    `import { ${className} } from '${importPath}';`,
    ``,
    `docs(${className}, {`,
    `  classDecorators: [`,
    `    // ApiTags('${sanitizeComment(ctrl.controllerPath ?? className.replace(/Controller$/, '').toLowerCase())}'),`,
    `  ],`,
    `  methods: {`,
    methodsBlock,
    `  },`,
    `});`,
    ``,
  ].join('\n');
}
