import fs from 'fs';
import os from 'os';
import path from 'path';
import { checkDocsVersionDrift } from '../../cli/docs-version-check';
import type { ControllerInfo } from '../../cli/extract-methods';

function makeController(dir: string, className: string, hasDocsFile = true): ControllerInfo {
  return {
    className,
    filePath: path.join(dir, `${className.toLowerCase()}.controller.ts`),
    controllerPath: null,
    methods: [],
    hasDocsFile,
    controllerRequiresAuth: false,
  };
}

function writeDocsFile(controllerFilePath: string, header: string): void {
  const docsFile = controllerFilePath.replace(/\.ts$/, '.docs.ts');
  fs.writeFileSync(docsFile, `${header}\n`, 'utf8');
}

describe('checkDocsVersionDrift()', () => {
  const dirs: string[] = [];

  afterEach(() => {
    for (const dir of dirs.splice(0)) {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });

  function makeDir(): string {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'nestjs-docfy-version-check-'));
    dirs.push(dir);
    return dir;
  }

  it('returns nothing when the stamped version matches the current version', () => {
    const dir = makeDir();
    const ctrl = makeController(dir, 'Users');
    writeDocsFile(ctrl.filePath, '// Generated by nestjs-docfy@0.12.0. Edit freely.');

    expect(checkDocsVersionDrift([ctrl], 'ts', '0.12.0')).toEqual([]);
  });

  it('flags a docs file stamped with an older version', () => {
    const dir = makeDir();
    const ctrl = makeController(dir, 'Users');
    writeDocsFile(ctrl.filePath, '// Generated by nestjs-docfy@0.9.0. Edit freely.');

    const result = checkDocsVersionDrift([ctrl], 'ts', '0.12.0');
    expect(result).toEqual([
      { controllerClass: 'Users', docsFile: ctrl.filePath.replace(/\.ts$/, '.docs.ts'), stampedVersion: '0.9.0' },
    ]);
  });

  it('flags a docs file with no version stamp at all (predates stamping)', () => {
    const dir = makeDir();
    const ctrl = makeController(dir, 'Users');
    writeDocsFile(ctrl.filePath, '// Generated by nestjs-docfy. Edit freely, use --force to merge new methods');

    const result = checkDocsVersionDrift([ctrl], 'ts', '0.12.0');
    expect(result).toEqual([
      { controllerClass: 'Users', docsFile: ctrl.filePath.replace(/\.ts$/, '.docs.ts'), stampedVersion: null },
    ]);
  });

  it('does not flag a docs file stamped with a newer version (e.g. local dev build ahead of the installed release)', () => {
    const dir = makeDir();
    const ctrl = makeController(dir, 'Users');
    writeDocsFile(ctrl.filePath, '// Generated by nestjs-docfy@1.0.0. Edit freely.');

    expect(checkDocsVersionDrift([ctrl], 'ts', '0.12.0')).toEqual([]);
  });

  it('skips controllers without a docs file', () => {
    const dir = makeDir();
    const ctrl = makeController(dir, 'Users', false);

    expect(checkDocsVersionDrift([ctrl], 'ts', '0.12.0')).toEqual([]);
  });

  it('skips a docs file with no recognizable header (e.g. hand-written, not generated)', () => {
    const dir = makeDir();
    const ctrl = makeController(dir, 'Users');
    writeDocsFile(ctrl.filePath, '// Hand-written docs file, not generated by nestjs-docfy.');

    expect(checkDocsVersionDrift([ctrl], 'ts', '0.12.0')).toEqual([]);
  });
});
