import fs from 'fs';
import os from 'os';
import path from 'path';
import { runDoctor, isDoctorReportClean } from '../../cli/doctor';

const TSCONFIG = JSON.stringify({
  compilerOptions: {
    module: 'commonjs',
    target: 'ES2020',
    experimentalDecorators: true,
    emitDecoratorMetadata: true,
    strict: true,
    skipLibCheck: true,
  },
  include: ['src'],
});

const CONTROLLER = `import { Controller, Get } from '@nestjs/common';

@Controller('users')
export class UsersController {
  @Get()
  findAll() {
    return [];
  }
}
`;

function docsFile(version: string): string {
  return `// Generated by nestjs-docfy@${version}. Edit freely, use --force to merge new methods, --overwrite to regenerate from scratch
import { docs } from 'nestjs-docfy';
import { UsersController } from './users.controller';

export default docs(UsersController, {
  methods: {
    findAll: [],
  },
});
`;
}

function makeProjectDir(files: Record<string, string>): string {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'nestjs-docfy-doctor-'));
  for (const [rel, content] of Object.entries(files)) {
    const full = path.join(dir, rel);
    fs.mkdirSync(path.dirname(full), { recursive: true });
    fs.writeFileSync(full, content, 'utf8');
  }
  return dir;
}

describe('runDoctor()', () => {
  const dirs: string[] = [];

  afterEach(() => {
    for (const dir of dirs.splice(0)) {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });

  function run(dir: string, currentVersion = '1.0.0') {
    return runDoctor(dir, { pattern: '**/*.controller.ts', format: 'ts', currentVersion });
  }

  it('reports a clean project with no issues', () => {
    const dir = makeProjectDir({
      'package.json': JSON.stringify({ name: 'app' }),
      'tsconfig.json': TSCONFIG,
      'src/users.controller.ts': CONTROLLER,
      'src/users.controller.docs.ts': docsFile('1.0.0'),
    });
    dirs.push(dir);

    const report = run(dir);
    expect(report.controllersScanned).toBe(1);
    expect(isDoctorReportClean(report)).toBe(true);
  });

  it('flags a controller with no companion docs file', () => {
    const dir = makeProjectDir({
      'package.json': JSON.stringify({ name: 'app' }),
      'tsconfig.json': TSCONFIG,
      'src/users.controller.ts': CONTROLLER,
    });
    dirs.push(dir);

    const report = run(dir);
    expect(isDoctorReportClean(report)).toBe(false);
    expect(report.controllerIssues).toEqual([
      expect.objectContaining({ controllerClass: 'UsersController', kind: 'missing-file' }),
    ]);
  });

  it('flags docfy-ui declared directly in the app package.json', () => {
    const dir = makeProjectDir({
      'package.json': JSON.stringify({ name: 'app', dependencies: { 'docfy-ui': '^0.1.0' } }),
      'tsconfig.json': TSCONFIG,
      'src/users.controller.ts': CONTROLLER,
      'src/users.controller.docs.ts': docsFile('1.0.0'),
    });
    dirs.push(dir);

    const report = run(dir);
    expect(isDoctorReportClean(report)).toBe(false);
    expect(report.docfyUiPin?.appDeclaredRange).toBe('^0.1.0');
  });

  it('flags a docs file stamped by an older nestjs-docfy version', () => {
    const dir = makeProjectDir({
      'package.json': JSON.stringify({ name: 'app' }),
      'tsconfig.json': TSCONFIG,
      'src/users.controller.ts': CONTROLLER,
      'src/users.controller.docs.ts': docsFile('0.9.0'),
    });
    dirs.push(dir);

    const report = run(dir, '1.0.0');
    expect(isDoctorReportClean(report)).toBe(false);
    expect(report.versionDrift).toEqual([
      expect.objectContaining({ controllerClass: 'UsersController', stampedVersion: '0.9.0' }),
    ]);
  });

  it('flags webpack: true without the compiler plugin registered', () => {
    const dir = makeProjectDir({
      'package.json': JSON.stringify({ name: 'app' }),
      'tsconfig.json': TSCONFIG,
      'nest-cli.json': JSON.stringify({ compilerOptions: { webpack: true } }),
      'src/users.controller.ts': CONTROLLER,
      'src/users.controller.docs.ts': docsFile('1.0.0'),
    });
    dirs.push(dir);

    const report = run(dir);
    expect(isDoctorReportClean(report)).toBe(false);
    expect(report.webpackMissingPlugin).toEqual(['']);
  });

  it('flags the compiler plugin being inert under SWC without typeCheck', () => {
    const dir = makeProjectDir({
      'package.json': JSON.stringify({ name: 'app' }),
      'tsconfig.json': TSCONFIG,
      'nest-cli.json': JSON.stringify({ compilerOptions: { builder: 'swc', plugins: ['nestjs-docfy'] } }),
      'src/users.controller.ts': CONTROLLER,
      'src/users.controller.docs.ts': docsFile('1.0.0'),
    });
    dirs.push(dir);

    const report = run(dir);
    expect(isDoctorReportClean(report)).toBe(false);
    expect(report.inertSwcPlugin).toEqual(['']);
  });
});
