import path from 'path';
import { renderDocsFile, relativeImport, inferSummary } from '../../cli/generate-file';
import type { ControllerInfo, InlineSchema } from '../../cli/extract-methods';

function makeCtrl(overrides: Partial<ControllerInfo> = {}): ControllerInfo {
  return {
    className: 'UsersController',
    filePath: '/project/src/users/users.controller.ts',
    controllerPath: 'users',
    hasDocsFile: false,
    controllerRequiresAuth: false,
    methods: [
      {
        name: 'findAll',
        httpDecorator: 'Get',
        httpPath: '',
        params: [],
        returnType: 'Promise<string[]>',
        responseType: null,
        isAsync: true,
        isInherited: false,
        inheritedFrom: null,
        requiresAuth: false,
      },
      {
        name: 'findOne',
        httpDecorator: 'Get',
        httpPath: ':id',
        params: [{ name: 'id', type: 'string', nestDecorator: '@Param', nestDecoratorArg: 'id', bodyType: null }],
        returnType: 'Promise<string>',
        responseType: null,
        isAsync: true,
        isInherited: false,
        inheritedFrom: null,
        requiresAuth: false,
      },
    ],
    ...overrides,
  };
}

const DOCS_PATH = '/project/src/users/users.controller.docs.ts';

describe('relativeImport()', () => {
  it('produces a relative path from docs file to controller', () => {
    const result = relativeImport(DOCS_PATH, '/project/src/users/users.controller.ts');
    expect(result).toBe('./users.controller');
  });

  it('handles cross-directory imports', () => {
    const result = relativeImport(
      '/project/src/docs/users.controller.docs.ts',
      '/project/src/users/users.controller.ts',
    );
    expect(result).toContain('../users/users.controller');
  });

  it('always starts with ./', () => {
    const result = relativeImport(DOCS_PATH, '/project/src/users/users.controller.ts');
    expect(result.startsWith('.')).toBe(true);
  });
});

describe('renderDocsFile() — ts format', () => {
  let output: string;
  beforeAll(() => {
    output = renderDocsFile(makeCtrl(), DOCS_PATH, 'ts');
  });

  it('contains the import from nestjs-docfy', () => {
    expect(output).toContain("from 'nestjs-docfy'");
  });

  it('contains the controller import', () => {
    expect(output).toContain('UsersController');
    expect(output).toContain('./users.controller');
  });

  it('contains docs() call', () => {
    expect(output).toContain('docs(UsersController,');
  });

  it('contains findAll method key', () => {
    expect(output).toContain('findAll:');
  });

  it('contains findOne method key', () => {
    expect(output).toContain('findOne:');
  });

  it('contains GET route in comment for findAll', () => {
    expect(output).toContain('GET');
  });

  it('contains :id path in comment for findOne', () => {
    expect(output).toContain(':id');
  });

  it('contains ApiOperation with inferred summary', () => {
    expect(output).toContain("ApiOperation({ summary: 'Find all' })");
  });

  it('contains ApiResponse ready to use', () => {
    expect(output).toContain('ApiResponse({ status:');
  });

  it('contains nestjs-docfy auto-generated comment', () => {
    expect(output).toContain('Generated by nestjs-docfy');
  });
});

describe('renderDocsFile() — js format', () => {
  let output: string;
  beforeAll(() => {
    output = renderDocsFile(makeCtrl(), DOCS_PATH.replace('.ts', '.js'), 'js');
  });

  it('uses require instead of import', () => {
    expect(output).toContain("require('nestjs-docfy')");
    expect(output).toContain('UsersController');
  });

  it('does not contain import keyword', () => {
    expect(output).not.toMatch(/^import /m);
  });
});

describe('renderDocsFile() — security: sanitisation', () => {
  it('does not inject code via malicious className', () => {
    const ctrl = makeCtrl({ className: 'Evil`); process.exit(1); docs(' });
    const output = renderDocsFile(ctrl, DOCS_PATH, 'ts');
    expect(output).not.toContain('process.exit');
    expect(output).toContain('Controller'); // fallback identifier used
  });

  it('does not inject code via malicious method name', () => {
    const ctrl = makeCtrl({
      methods: [{
        name: 'evil`); process.exit(1);//',
        httpDecorator: null, httpPath: null, params: [],
        returnType: 'void', responseType: null, isAsync: false, isInherited: false, inheritedFrom: null, requiresAuth: false,
      }],
    });
    const output = renderDocsFile(ctrl, DOCS_PATH, 'ts');
    expect(output).not.toContain('process.exit');
  });

  it('does not break out of string literals via malicious controllerPath', () => {
    // controllerPath appears only inside a comment — the real risk is breaking
    // out of a string/template literal into executable code. Verify that
    // string-breaking characters are stripped.
    const ctrl = makeCtrl({ controllerPath: "'); require('child_process').execSync('id')//" });
    const output = renderDocsFile(ctrl, DOCS_PATH, 'ts');
    // The dangerous characters ' and ) must not appear outside of a comment context
    // We verify the import/docs() call lines are not corrupted
    const codeLines = output.split('\n').filter((l) => !l.trimStart().startsWith('//') && !l.trimStart().startsWith('*'));
    expect(codeLines.join('\n')).not.toContain("require('child_process')");
  });

  it('does not break out of comment blocks via malicious returnType', () => {
    // returnType appears in a line comment — the real risk is closing a block
    // comment with */ and injecting code after it. Verify * is stripped.
    const ctrl = makeCtrl({
      methods: [{
        name: 'findAll',
        httpDecorator: 'Get', httpPath: null, params: [],
        returnType: '*/ require("child_process").execSync("id") /*',
        responseType: null, isAsync: false, isInherited: false, inheritedFrom: null, requiresAuth: false,
      }],
    });
    const output = renderDocsFile(ctrl, DOCS_PATH, 'ts');
    // * is stripped by sanitizeComment, so */ cannot appear from returnType
    expect(output).not.toContain('require("child_process")');
  });
});

describe('renderDocsFile() — edge cases', () => {
  it('handles controller with no methods gracefully', () => {
    const ctrl = makeCtrl({ methods: [] });
    const output = renderDocsFile(ctrl, DOCS_PATH, 'ts');
    expect(output).toContain('No public HTTP methods found');
  });

  it('handles null controllerPath (no route argument)', () => {
    const ctrl = makeCtrl({ controllerPath: null });
    expect(() => renderDocsFile(ctrl, DOCS_PATH, 'ts')).not.toThrow();
  });

  it('handles inherited method with inheritedFrom label', () => {
    const ctrl = makeCtrl({
      methods: [{
        name: 'findAll',
        httpDecorator: 'Get', httpPath: null, params: [],
        returnType: 'unknown',
        responseType: null, isAsync: false, isInherited: true, inheritedFrom: 'CrudBase', requiresAuth: false,
      }],
    });
    const output = renderDocsFile(ctrl, DOCS_PATH, 'ts');
    expect(output).toContain('CrudBase');
  });
});

// ---------------------------------------------------------------------------
// inferSummary()
// ---------------------------------------------------------------------------

describe('inferSummary()', () => {
  it('capitalizes first word, lowercases rest', () => {
    expect(inferSummary('findAll')).toBe('Find all');
  });

  it('splits multi-word camelCase', () => {
    expect(inferSummary('createUser')).toBe('Create user');
  });

  it('handles longer chains', () => {
    expect(inferSummary('getProfileById')).toBe('Get profile by id');
  });

  it('handles single word', () => {
    expect(inferSummary('login')).toBe('Login');
  });

  it('handles acronym prefix (HTTP)', () => {
    expect(inferSummary('refreshToken')).toBe('Refresh token');
  });

  it('handles delete prefix', () => {
    expect(inferSummary('deleteById')).toBe('Delete by id');
  });

  it('returns empty string for empty input', () => {
    expect(inferSummary('')).toBe('');
  });

  it('does not inject code via malicious method name (summary is sanitized at render)', () => {
    // inferSummary itself just transforms — sanitizeIdentifier blocks bad names before render
    const result = inferSummary('findAll');
    expect(result).not.toContain("'");
    expect(result).not.toContain('"');
  });
});

// ---------------------------------------------------------------------------
// Response type — ApiResponse with DTO type
// ---------------------------------------------------------------------------

describe('renderDocsFile() — responseType', () => {
  const DTO_PATH = '/project/src/users/user-response.dto.ts';

  it('renders ApiResponse with type for a named DTO', () => {
    const ctrl = makeCtrl({
      methods: [{
        name: 'findOne',
        httpDecorator: 'Get',
        httpPath: ':id',
        params: [],
        returnType: 'Promise<UserResponseDto>',
        responseType: { name: 'UserResponseDto', absolutePath: DTO_PATH, isArray: false, isInterface: false },
        isAsync: true, isInherited: false, inheritedFrom: null, requiresAuth: false,
      }],
    });
    const output = renderDocsFile(ctrl, DOCS_PATH, 'ts');
    expect(output).toContain("ApiResponse({ status: 200, description: 'OK', type: UserResponseDto })");
  });

  it('renders ApiResponse with array type for DTO[]', () => {
    const ctrl = makeCtrl({
      methods: [{
        name: 'findAll',
        httpDecorator: 'Get',
        httpPath: '',
        params: [],
        returnType: 'Promise<UserResponseDto[]>',
        responseType: { name: 'UserResponseDto', absolutePath: DTO_PATH, isArray: true, isInterface: false },
        isAsync: true, isInherited: false, inheritedFrom: null, requiresAuth: false,
      }],
    });
    const output = renderDocsFile(ctrl, DOCS_PATH, 'ts');
    expect(output).toContain("ApiResponse({ status: 200, description: 'OK', type: [UserResponseDto] })");
  });

  it('adds import for the DTO when responseType is set', () => {
    const ctrl = makeCtrl({
      methods: [{
        name: 'findOne',
        httpDecorator: 'Get',
        httpPath: ':id',
        params: [],
        returnType: 'Promise<UserResponseDto>',
        responseType: { name: 'UserResponseDto', absolutePath: DTO_PATH, isArray: false, isInterface: false },
        isAsync: true, isInherited: false, inheritedFrom: null, requiresAuth: false,
      }],
    });
    const output = renderDocsFile(ctrl, DOCS_PATH, 'ts');
    expect(output).toContain("import { UserResponseDto } from './user-response.dto'");
  });

  it('deduplicates imports when same DTO used in multiple methods', () => {
    const ctrl = makeCtrl({
      methods: [
        {
          name: 'findOne',
          httpDecorator: 'Get', httpPath: ':id', params: [],
          returnType: 'Promise<UserResponseDto>',
          responseType: { name: 'UserResponseDto', absolutePath: DTO_PATH, isArray: false, isInterface: false },
          isAsync: true, isInherited: false, inheritedFrom: null, requiresAuth: false,
        },
        {
          name: 'update',
          httpDecorator: 'Put', httpPath: ':id', params: [],
          returnType: 'Promise<UserResponseDto>',
          responseType: { name: 'UserResponseDto', absolutePath: DTO_PATH, isArray: false, isInterface: false },
          isAsync: true, isInherited: false, inheritedFrom: null, requiresAuth: false,
        },
      ],
    });
    const output = renderDocsFile(ctrl, DOCS_PATH, 'ts');
    const importMatches = (output.match(/import \{ UserResponseDto \}/g) ?? []).length;
    expect(importMatches).toBe(1);
  });

  it('falls back to ApiResponse without type for null responseType', () => {
    const ctrl = makeCtrl({
      methods: [{
        name: 'findAll',
        httpDecorator: 'Get', httpPath: '', params: [],
        returnType: 'Promise<string[]>',
        responseType: null,
        isAsync: true, isInherited: false, inheritedFrom: null, requiresAuth: false,
      }],
    });
    const output = renderDocsFile(ctrl, DOCS_PATH, 'ts');
    expect(output).toContain("ApiResponse({ status: 200, description: 'OK' })");
    expect(output).not.toContain('type:');
  });

  it('skips import for responseType with invalid identifier name', () => {
    const ctrl = makeCtrl({
      methods: [{
        name: 'findOne',
        httpDecorator: 'Get', httpPath: ':id', params: [],
        returnType: 'Promise<unknown>',
        responseType: { name: '123Invalid', absolutePath: DTO_PATH, isArray: false, isInterface: false },
        isAsync: true, isInherited: false, inheritedFrom: null, requiresAuth: false,
      }],
    });
    const output = renderDocsFile(ctrl, DOCS_PATH, 'ts');
    expect(output).not.toContain('123Invalid');
    expect(output).toContain("ApiResponse({ status: 200, description: 'OK' })");
  });

  it('renders correct import path for cross-directory DTO', () => {
    const crossDirDtoPath = '/project/src/dto/shared-response.dto.ts';
    const ctrl = makeCtrl({
      methods: [{
        name: 'getShared',
        httpDecorator: 'Get', httpPath: 'shared', params: [],
        returnType: 'Promise<SharedResponseDto>',
        responseType: { name: 'SharedResponseDto', absolutePath: crossDirDtoPath, isArray: false, isInterface: false },
        isAsync: true, isInherited: false, inheritedFrom: null, requiresAuth: false,
      }],
    });
    const output = renderDocsFile(ctrl, DOCS_PATH, 'ts');
    expect(output).toContain("import { SharedResponseDto } from '../dto/shared-response.dto'");
  });

  it('renders require() for JS format with responseType', () => {
    const ctrl = makeCtrl({
      methods: [{
        name: 'findOne',
        httpDecorator: 'Get', httpPath: ':id', params: [],
        returnType: 'Promise<UserResponseDto>',
        responseType: { name: 'UserResponseDto', absolutePath: DTO_PATH, isArray: false, isInterface: false },
        isAsync: true, isInherited: false, inheritedFrom: null, requiresAuth: false,
      }],
    });
    const output = renderDocsFile(ctrl, DOCS_PATH.replace('.ts', '.js'), 'js');
    expect(output).toContain("require('./user-response.dto')");
    expect(output).toContain('UserResponseDto');
  });
});

// ---------------------------------------------------------------------------
// ApiParam / ApiQuery / ApiBody — param decorator generation
// ---------------------------------------------------------------------------

const DTO_PATH = '/project/src/users/user-request.dto.ts';

function makeParam(
  overrides: Partial<import('../../cli/extract-methods').ParamInfo>,
): import('../../cli/extract-methods').ParamInfo {
  return {
    name: 'p',
    type: 'string',
    nestDecorator: null,
    nestDecoratorArg: null,
    bodyType: null,
    ...overrides,
  };
}

describe('renderDocsFile() — @ApiParam', () => {
  it('generates ApiParam for @Param with named argument', () => {
    const ctrl = makeCtrl({
      methods: [{
        name: 'findOne', httpDecorator: 'Get', httpPath: ':id',
        params: [makeParam({ nestDecorator: '@Param', nestDecoratorArg: 'id', type: 'string' })],
        returnType: 'string', responseType: null,
        isAsync: false, isInherited: false, inheritedFrom: null, requiresAuth: false,
      }],
    });
    const output = renderDocsFile(ctrl, DOCS_PATH, 'ts');
    expect(output).toContain("ApiParam({ name: 'id', type: String })");
  });

  it('includes ApiParam in swagger import', () => {
    const ctrl = makeCtrl({
      methods: [{
        name: 'findOne', httpDecorator: 'Get', httpPath: ':id',
        params: [makeParam({ nestDecorator: '@Param', nestDecoratorArg: 'id', type: 'string' })],
        returnType: 'string', responseType: null,
        isAsync: false, isInherited: false, inheritedFrom: null, requiresAuth: false,
      }],
    });
    const output = renderDocsFile(ctrl, DOCS_PATH, 'ts');
    expect(output).toContain('ApiParam');
    expect(output).toMatch(/import \{[^}]*ApiParam[^}]*\} from '@nestjs\/swagger'/);
  });

  it('skips ApiParam when @Param has no named argument (object param)', () => {
    const ctrl = makeCtrl({
      methods: [{
        name: 'findOne', httpDecorator: 'Get', httpPath: ':id',
        params: [makeParam({ nestDecorator: '@Param', nestDecoratorArg: null, type: 'object' })],
        returnType: 'string', responseType: null,
        isAsync: false, isInherited: false, inheritedFrom: null, requiresAuth: false,
      }],
    });
    const output = renderDocsFile(ctrl, DOCS_PATH, 'ts');
    expect(output).not.toContain('ApiParam');
  });

  it('sanitizes malicious param name', () => {
    const ctrl = makeCtrl({
      methods: [{
        name: 'findOne', httpDecorator: 'Get', httpPath: ':id',
        params: [makeParam({ nestDecorator: '@Param', nestDecoratorArg: "id'); process.exit(1);//", type: 'string' })],
        returnType: 'string', responseType: null,
        isAsync: false, isInherited: false, inheritedFrom: null, requiresAuth: false,
      }],
    });
    const output = renderDocsFile(ctrl, DOCS_PATH, 'ts');
    expect(output).not.toContain('process.exit');
  });
});

describe('renderDocsFile() — @ApiQuery', () => {
  it('generates ApiQuery for @Query with named argument', () => {
    const ctrl = makeCtrl({
      methods: [{
        name: 'search', httpDecorator: 'Get', httpPath: '',
        params: [makeParam({ nestDecorator: '@Query', nestDecoratorArg: 'q', type: 'string' })],
        returnType: 'string[]', responseType: null,
        isAsync: false, isInherited: false, inheritedFrom: null, requiresAuth: false,
      }],
    });
    const output = renderDocsFile(ctrl, DOCS_PATH, 'ts');
    expect(output).toContain("ApiQuery({ name: 'q', type: String");
  });

  it('generates ApiQuery with Number type for numeric query param', () => {
    const ctrl = makeCtrl({
      methods: [{
        name: 'list', httpDecorator: 'Get', httpPath: '',
        params: [makeParam({ nestDecorator: '@Query', nestDecoratorArg: 'page', type: 'number' })],
        returnType: 'string[]', responseType: null,
        isAsync: false, isInherited: false, inheritedFrom: null, requiresAuth: false,
      }],
    });
    const output = renderDocsFile(ctrl, DOCS_PATH, 'ts');
    expect(output).toContain("ApiQuery({ name: 'page', type: Number");
  });

  it('includes ApiQuery in swagger import', () => {
    const ctrl = makeCtrl({
      methods: [{
        name: 'search', httpDecorator: 'Get', httpPath: '',
        params: [makeParam({ nestDecorator: '@Query', nestDecoratorArg: 'q', type: 'string' })],
        returnType: 'string[]', responseType: null,
        isAsync: false, isInherited: false, inheritedFrom: null, requiresAuth: false,
      }],
    });
    const output = renderDocsFile(ctrl, DOCS_PATH, 'ts');
    expect(output).toMatch(/import \{[^}]*ApiQuery[^}]*\} from '@nestjs\/swagger'/);
  });
});

describe('renderDocsFile() — @ApiBody', () => {
  it('generates ApiBody with DTO type when bodyType is resolved', () => {
    const ctrl = makeCtrl({
      methods: [{
        name: 'create', httpDecorator: 'Post', httpPath: '',
        params: [makeParam({
          nestDecorator: '@Body', nestDecoratorArg: null, type: 'CreateUserDto',
          bodyType: { name: 'CreateUserDto', absolutePath: DTO_PATH, isArray: false, isInterface: false },
        })],
        returnType: 'void', responseType: null,
        isAsync: true, isInherited: false, inheritedFrom: null, requiresAuth: false,
      }],
    });
    const output = renderDocsFile(ctrl, DOCS_PATH, 'ts');
    expect(output).toContain('ApiBody({ type: CreateUserDto })');
  });

  it('adds import for the body DTO', () => {
    const ctrl = makeCtrl({
      methods: [{
        name: 'create', httpDecorator: 'Post', httpPath: '',
        params: [makeParam({
          nestDecorator: '@Body', nestDecoratorArg: null, type: 'CreateUserDto',
          bodyType: { name: 'CreateUserDto', absolutePath: DTO_PATH, isArray: false, isInterface: false },
        })],
        returnType: 'void', responseType: null,
        isAsync: true, isInherited: false, inheritedFrom: null, requiresAuth: false,
      }],
    });
    const output = renderDocsFile(ctrl, DOCS_PATH, 'ts');
    expect(output).toContain("import { CreateUserDto } from './user-request.dto'");
  });

  it('includes ApiBody in swagger import', () => {
    const ctrl = makeCtrl({
      methods: [{
        name: 'create', httpDecorator: 'Post', httpPath: '',
        params: [makeParam({
          nestDecorator: '@Body', nestDecoratorArg: null, type: 'CreateUserDto',
          bodyType: { name: 'CreateUserDto', absolutePath: DTO_PATH, isArray: false, isInterface: false },
        })],
        returnType: 'void', responseType: null,
        isAsync: true, isInherited: false, inheritedFrom: null, requiresAuth: false,
      }],
    });
    const output = renderDocsFile(ctrl, DOCS_PATH, 'ts');
    expect(output).toMatch(/import \{[^}]*ApiBody[^}]*\} from '@nestjs\/swagger'/);
  });

  it('skips ApiBody for @Body with field selector', () => {
    const ctrl = makeCtrl({
      methods: [{
        name: 'create', httpDecorator: 'Post', httpPath: '',
        params: [makeParam({ nestDecorator: '@Body', nestDecoratorArg: 'email', type: 'string' })],
        returnType: 'void', responseType: null,
        isAsync: true, isInherited: false, inheritedFrom: null, requiresAuth: false,
      }],
    });
    const output = renderDocsFile(ctrl, DOCS_PATH, 'ts');
    expect(output).not.toContain('ApiBody');
  });

  it('deduplicates import when same DTO used in body and response', () => {
    const ctrl = makeCtrl({
      methods: [{
        name: 'update', httpDecorator: 'Put', httpPath: ':id',
        params: [makeParam({
          nestDecorator: '@Body', nestDecoratorArg: null, type: 'UserDto',
          bodyType: { name: 'UserDto', absolutePath: DTO_PATH, isArray: false, isInterface: false },
        })],
        returnType: 'Promise<UserDto>',
        responseType: { name: 'UserDto', absolutePath: DTO_PATH, isArray: false, isInterface: false },
        isAsync: true, isInherited: false, inheritedFrom: null, requiresAuth: false,
      }],
    });
    const output = renderDocsFile(ctrl, DOCS_PATH, 'ts');
    const importMatches = (output.match(/import \{ UserDto \}/g) ?? []).length;
    expect(importMatches).toBe(1);
  });

  it('does not add ApiBody import when no methods use @Body', () => {
    const ctrl = makeCtrl(); // default methods have no @Body
    const output = renderDocsFile(ctrl, DOCS_PATH, 'ts');
    expect(output).not.toContain('ApiBody');
  });
});

// ---------------------------------------------------------------------------
// ApiBearerAuth — auth guard detection
// ---------------------------------------------------------------------------

describe('renderDocsFile() — @ApiBearerAuth', () => {
  it('emits ApiBearerAuth() in method block when requiresAuth=true', () => {
    const ctrl = makeCtrl({
      methods: [{
        name: 'getProfile', httpDecorator: 'Get', httpPath: 'profile',
        params: [], returnType: 'string', responseType: null,
        isAsync: false, isInherited: false, inheritedFrom: null, requiresAuth: true,
      }],
    });
    const output = renderDocsFile(ctrl, DOCS_PATH, 'ts');
    expect(output).toContain('ApiBearerAuth()');
  });

  it('adds ApiBearerAuth to swagger import when any method requiresAuth', () => {
    const ctrl = makeCtrl({
      methods: [{
        name: 'getProfile', httpDecorator: 'Get', httpPath: 'profile',
        params: [], returnType: 'string', responseType: null,
        isAsync: false, isInherited: false, inheritedFrom: null, requiresAuth: true,
      }],
    });
    const output = renderDocsFile(ctrl, DOCS_PATH, 'ts');
    expect(output).toMatch(/import \{[^}]*ApiBearerAuth[^}]*\} from '@nestjs\/swagger'/);
  });

  it('emits ApiBearerAuth() in classDecorators when controllerRequiresAuth=true', () => {
    const ctrl = makeCtrl({ controllerRequiresAuth: true });
    const output = renderDocsFile(ctrl, DOCS_PATH, 'ts');
    const classBlock = output.substring(
      output.indexOf('classDecorators'),
      output.indexOf('methods:'),
    );
    expect(classBlock).toContain('ApiBearerAuth()');
  });

  it('does not emit ApiBearerAuth() when requiresAuth=false', () => {
    const ctrl = makeCtrl(); // default: requiresAuth: false
    const output = renderDocsFile(ctrl, DOCS_PATH, 'ts');
    expect(output).not.toContain('ApiBearerAuth');
  });

  it('only one method has ApiBearerAuth when partial auth', () => {
    const ctrl = makeCtrl({
      methods: [
        {
          name: 'public', httpDecorator: 'Get', httpPath: 'pub',
          params: [], returnType: 'string', responseType: null,
          isAsync: false, isInherited: false, inheritedFrom: null, requiresAuth: false,
        },
        {
          name: 'private', httpDecorator: 'Get', httpPath: 'priv',
          params: [], returnType: 'string', responseType: null,
          isAsync: false, isInherited: false, inheritedFrom: null, requiresAuth: true,
        },
      ],
    });
    const output = renderDocsFile(ctrl, DOCS_PATH, 'ts');
    const bearerMatches = (output.match(/ApiBearerAuth\(\)/g) ?? []).length;
    expect(bearerMatches).toBe(1); // only the private method
  });
});

describe('renderDocsFile() — error responses', () => {
  it('emits 400 response when method has a @Body param', () => {
    const ctrl = makeCtrl({
      methods: [{
        name: 'create', httpDecorator: 'Post', httpPath: '',
        params: [{ name: 'dto', type: 'CreateDto', nestDecorator: '@Body', nestDecoratorArg: null, bodyType: null }],
        returnType: 'void', responseType: null,
        isAsync: false, isInherited: false, inheritedFrom: null, requiresAuth: false,
      }],
    });
    const output = renderDocsFile(ctrl, DOCS_PATH, 'ts');
    expect(output).toContain("ApiResponse({ status: 400, description: 'Bad Request' })");
  });

  it('does NOT emit 400 when @Body has a field selector', () => {
    const ctrl = makeCtrl({
      methods: [{
        name: 'create', httpDecorator: 'Post', httpPath: '',
        params: [{ name: 'name', type: 'string', nestDecorator: '@Body', nestDecoratorArg: 'name', bodyType: null }],
        returnType: 'void', responseType: null,
        isAsync: false, isInherited: false, inheritedFrom: null, requiresAuth: false,
      }],
    });
    const output = renderDocsFile(ctrl, DOCS_PATH, 'ts');
    expect(output).not.toContain("status: 400");
  });

  it('emits 401 response when requiresAuth=true', () => {
    const ctrl = makeCtrl({
      methods: [{
        name: 'getProfile', httpDecorator: 'Get', httpPath: 'profile',
        params: [], returnType: 'string', responseType: null,
        isAsync: false, isInherited: false, inheritedFrom: null, requiresAuth: true,
      }],
    });
    const output = renderDocsFile(ctrl, DOCS_PATH, 'ts');
    expect(output).toContain("ApiResponse({ status: 401, description: 'Unauthorized' })");
  });

  it('does NOT emit 401 when requiresAuth=false', () => {
    const ctrl = makeCtrl({
      methods: [{
        name: 'list', httpDecorator: 'Get', httpPath: '',
        params: [], returnType: 'string', responseType: null,
        isAsync: false, isInherited: false, inheritedFrom: null, requiresAuth: false,
      }],
    });
    const output = renderDocsFile(ctrl, DOCS_PATH, 'ts');
    expect(output).not.toContain("status: 401");
  });

  it('emits both 400 and 401 when method has body and requires auth', () => {
    const ctrl = makeCtrl({
      methods: [{
        name: 'create', httpDecorator: 'Post', httpPath: '',
        params: [{ name: 'dto', type: 'CreateDto', nestDecorator: '@Body', nestDecoratorArg: null, bodyType: null }],
        returnType: 'void', responseType: null,
        isAsync: false, isInherited: false, inheritedFrom: null, requiresAuth: true,
      }],
    });
    const output = renderDocsFile(ctrl, DOCS_PATH, 'ts');
    expect(output).toContain("status: 400");
    expect(output).toContain("status: 401");
  });

  it('includes description on success response', () => {
    const ctrl = makeCtrl({
      methods: [{
        name: 'create', httpDecorator: 'Post', httpPath: '',
        params: [], returnType: 'void', responseType: null,
        isAsync: false, isInherited: false, inheritedFrom: null, requiresAuth: false,
      }],
    });
    const output = renderDocsFile(ctrl, DOCS_PATH, 'ts');
    expect(output).toContain("description: 'Created'");
  });
});

const DTO_PATH_IFACE = '/project/src/users/register-response.dto.ts';

function makeInterfaceResponseType(overrides: Partial<{ isArray: boolean; schema: InlineSchema }> = {}) {
  const schema: InlineSchema = overrides.schema ?? {
    properties: {
      success: { type: 'boolean' },
      message: { type: 'string', nullable: true },
    },
    required: ['success'],
  };
  return {
    name: 'RegisterResponseDto',
    absolutePath: DTO_PATH_IFACE,
    isArray: overrides.isArray ?? false,
    isInterface: true,
    inlineSchema: schema,
  };
}

describe('renderDocsFile() — interface DTO → schema:', () => {
  it('emits schema: object instead of type: for interface response', () => {
    const ctrl = makeCtrl({
      methods: [{
        name: 'register', httpDecorator: 'Post', httpPath: '',
        params: [], returnType: 'Promise<RegisterResponseDto>',
        responseType: makeInterfaceResponseType(),
        isAsync: true, isInherited: false, inheritedFrom: null, requiresAuth: false,
      }],
    });
    const output = renderDocsFile(ctrl, DOCS_PATH, 'ts');
    expect(output).toContain("schema:");
    expect(output).toContain("type: 'object'");
    expect(output).toContain("type: 'boolean'");
    expect(output).toContain("type: 'string'");
    expect(output).toContain("nullable: true");
    expect(output).toContain("required: ['success']");
  });

  it('does NOT emit type: RegisterResponseDto (no runtime value reference)', () => {
    const ctrl = makeCtrl({
      methods: [{
        name: 'register', httpDecorator: 'Post', httpPath: '',
        params: [], returnType: 'Promise<RegisterResponseDto>',
        responseType: makeInterfaceResponseType(),
        isAsync: true, isInherited: false, inheritedFrom: null, requiresAuth: false,
      }],
    });
    const output = renderDocsFile(ctrl, DOCS_PATH, 'ts');
    expect(output).not.toContain('type: RegisterResponseDto');
  });

  it('does NOT import the interface (no runtime value to import)', () => {
    const ctrl = makeCtrl({
      methods: [{
        name: 'register', httpDecorator: 'Post', httpPath: '',
        params: [], returnType: 'Promise<RegisterResponseDto>',
        responseType: makeInterfaceResponseType(),
        isAsync: true, isInherited: false, inheritedFrom: null, requiresAuth: false,
      }],
    });
    const output = renderDocsFile(ctrl, DOCS_PATH, 'ts');
    expect(output).not.toContain("import { RegisterResponseDto }");
  });

  it('wraps schema in type:array + items when isArray=true', () => {
    const ctrl = makeCtrl({
      methods: [{
        name: 'list', httpDecorator: 'Get', httpPath: '',
        params: [], returnType: 'Promise<RegisterResponseDto[]>',
        responseType: makeInterfaceResponseType({ isArray: true }),
        isAsync: true, isInherited: false, inheritedFrom: null, requiresAuth: false,
      }],
    });
    const output = renderDocsFile(ctrl, DOCS_PATH, 'ts');
    expect(output).toContain("type: 'array'");
    expect(output).toContain("items:");
  });

  it('emits schema: for interface @Body params', () => {
    const ctrl = makeCtrl({
      methods: [{
        name: 'register', httpDecorator: 'Post', httpPath: '',
        params: [{
          name: 'body', type: 'RegisterResponseDto',
          nestDecorator: '@Body', nestDecoratorArg: null,
          bodyType: makeInterfaceResponseType(),
        }],
        returnType: 'void', responseType: null,
        isAsync: false, isInherited: false, inheritedFrom: null, requiresAuth: false,
      }],
    });
    const output = renderDocsFile(ctrl, DOCS_PATH, 'ts');
    expect(output).toContain('ApiBody({ schema:');
    expect(output).not.toContain('import { RegisterResponseDto }');
  });

  it('handles interface with no properties gracefully', () => {
    const ctrl = makeCtrl({
      methods: [{
        name: 'register', httpDecorator: 'Post', httpPath: '',
        params: [], returnType: 'Promise<EmptyDto>',
        responseType: {
          name: 'EmptyDto', absolutePath: DTO_PATH_IFACE,
          isArray: false, isInterface: true,
          inlineSchema: { properties: {}, required: [] },
        },
        isAsync: true, isInherited: false, inheritedFrom: null, requiresAuth: false,
      }],
    });
    const output = renderDocsFile(ctrl, DOCS_PATH, 'ts');
    expect(output).toContain("schema:");
    expect(output).not.toContain('type: EmptyDto');
  });
});
